Project 1/force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project 1/force-app/main/default/objects/Address__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Adresses</relationshipLabel>
    <relationshipName>Adresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project 1/force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project 1/force-app/main/default/objects/Address__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project 1/force-app/main/default/classes/contactUtilityClass.cls
public with sharing class contactUtilityClass {
    
    public static List<Contact> newAddress(List<Contact> cons){

        List<Address__c> addressList = new List<Address__c>();

        for (Contact c : cons) {
            Address__c newAddress = new Address__c(Name = c.FirstName + ' ' + c.LastName, Street_Address__C = c.MailingStreet,
                                                    City__c = c.MailingCity, State__c = c.MailingState,
                                                    Zip_Code__c = c.MailingPostalCode, Contact__c = c.Id);
            addressList.add(newAddress);
        }

        insert addressList;

        return cons;

    }

    public static List<Contact> updateAddress(List<Contact> cons){

        List<Id> conIds = new List<Id>();

        for (Contact c : cons) {

            conIds.add(c.Id);
            
        }

        List<Address__c> conAddresses = new List<Address__c>([SELECT Street_Address__C, City__c, State__c, Zip_Code__C
                                                                FROM Address__c WHERE Contact__c IN :conIds]);

        for (Address__c a: conAddresses){
            
            for (Contact c : cons){

                if (a.Street_Address__C != c.MailingStreet || 
                    a.City__c != c.MailingCity||
                    a.State__c != c.MailingState||
                    a.Zip_Code__c != c.MailingPostalCode) {

                        a.Street_Address__C = c.MailingStreet; 
                        a.City__c = c.MailingCity;
                        a.State__c = c.MailingState;
                        a.Zip_Code__c = c.MailingPostalCode;
                    
                }
            }
        }

        update conAddresses;

        return cons;

    }

}